name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - conda-package-handling
  - flake8
  - joblib
  - pip
  - pygithub
  - pytest
  - python-rapidjson
  - pyyaml
  - requests
  - tqdm
  - wget
