name: conda-forge-artifact-validation
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - conda-package-handling
  - flake8
  - joblib
  - pip
  - pytest
  - python-rapidjson
  - python=3.8
  - pyyaml
  - requests
  - tqdm
  - wget
