name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - click
  - conda-package-handling
  - curl
  - flake8
  - joblib
  - pip
  - pygithub
  - pytest
  - python-rapidjson
  - pyyaml
  - requests
  - tenacity
  - tqdm
  - wget
  - setuptools_scm
  - setuptools_scm_git_archive
  - importlib_metadata
