allowed:
- conda-package-handling
files:
- Lib/site-packages/conda_package_handling-*.dist-info/**/*
- Lib/site-packages/conda_package_handling-*.egg
- Lib/site-packages/conda_package_handling-*.egg-info
- Lib/site-packages/conda_package_handling-*.egg-info/**/*
- Lib/site-packages/conda_package_handling/**/*
- Scripts/cph-script.py
- Scripts/cph.exe
- bin/cph
- lib/python*/site-packages/conda_package_handling-*.dist-info/**/*
- lib/python*/site-packages/conda_package_handling-*.egg
- lib/python*/site-packages/conda_package_handling-*.egg-info
- lib/python*/site-packages/conda_package_handling-*.egg-info/**/*
- lib/python*/site-packages/conda_package_handling/**/*
- site-packages/conda_package_handling-*.dist-info/**/*
- site-packages/conda_package_handling-*.egg-info/**/*
- site-packages/conda_package_handling/**/*
