allowed:
- conda-build
files:
- Lib/distutils/command/bdist_conda.py
- Lib/site-packages/conda_build-*.dist-info/**/*
- Lib/site-packages/conda_build-*.egg
- Lib/site-packages/conda_build-*.egg-info
- Lib/site-packages/conda_build-*.egg-info/**/*
- Lib/site-packages/conda_build/**/*
- Scripts/conda-build-script.py
- Scripts/conda-build.exe
- Scripts/conda-convert-script.py
- Scripts/conda-convert.exe
- Scripts/conda-debug-script.py
- Scripts/conda-debug.exe
- Scripts/conda-develop-script.py
- Scripts/conda-develop.exe
- Scripts/conda-index-script.py
- Scripts/conda-index.exe
- Scripts/conda-inspect-script.py
- Scripts/conda-inspect.exe
- Scripts/conda-metapackage-script.py
- Scripts/conda-metapackage.exe
- Scripts/conda-render-script.py
- Scripts/conda-render.exe
- Scripts/conda-sign-script.py
- Scripts/conda-sign.exe
- Scripts/conda-skeleton-script.py
- Scripts/conda-skeleton.exe
- bin/conda-build
- bin/conda-convert
- bin/conda-debug
- bin/conda-develop
- bin/conda-index
- bin/conda-inspect
- bin/conda-metapackage
- bin/conda-render
- bin/conda-sign
- bin/conda-skeleton
- lib/python*/site-packages/conda_build-*.dist-info/**/*
- lib/python*/site-packages/conda_build-*.egg
- lib/python*/site-packages/conda_build-*.egg-info
- lib/python*/site-packages/conda_build-*.egg-info/**/*
- lib/python*/site-packages/conda_build/**/*
- lib/python2.7/distutils/command/bdist_conda.py
- lib/python3.10/distutils/command/bdist_conda.py
- lib/python3.4/distutils/command/bdist_conda.py
- lib/python3.5/distutils/command/bdist_conda.py
- lib/python3.6/distutils/command/bdist_conda.py
- lib/python3.7/distutils/command/bdist_conda.py
- lib/python3.8/distutils/command/bdist_conda.py
- lib/python3.9/distutils/command/bdist_conda.py
- site-packages/conda_build-*.dist-info/**/*
- site-packages/conda_build-*.egg-info/**/*
- site-packages/conda_build/**/*
