allowed:
- conda
- conda-env
files:
- Lib/site-packages/conda-*.dist-info/**/*
- Lib/site-packages/conda-*.egg
- Lib/site-packages/conda-*.egg-info
- Lib/site-packages/conda-*.egg-info/**/*
- Lib/site-packages/conda/**/*
- Lib/site-packages/conda_env-*.dist-info/**/*
- Lib/site-packages/conda_env-*.egg
- Lib/site-packages/conda_env-*.egg-info
- Lib/site-packages/conda_env-*.egg-info/**/*
- Lib/site-packages/conda_env/**/*
- Lib/site-packages/xonsh/conda.xsh
- Lib/site-packages/xontrib/conda.xsh
- Library/bin/conda.bat
- Scripts/activate
- Scripts/activate.bat
- Scripts/conda-env-script.py
- Scripts/conda-env.exe
- Scripts/conda-script.py
- Scripts/conda.exe
- Scripts/deactivate
- Scripts/deactivate.bat
- bin/activate
- bin/conda
- bin/conda-env
- bin/deactivate
- condabin/_conda_activate.bat
- condabin/activate.bat
- condabin/conda
- condabin/conda.bat
- condabin/conda_auto_activate.bat
- condabin/conda_hook.bat
- condabin/deactivate.bat
- condabin/rename_tmp.bat
- etc/bash_completion.d/conda
- etc/conda_bash.sh
- etc/fish/conf.d/conda.fish
- etc/profile.d/conda.csh
- etc/profile.d/conda.sh
- exec/activate
- exec/activate.bat
- exec/conda
- exec/conda-script.py
- exec/conda.bat
- exec/conda.exe
- exec/deactivate
- lib/python*/site-packages/conda-*.dist-info/**/*
- lib/python*/site-packages/conda-*.egg
- lib/python*/site-packages/conda-*.egg-info
- lib/python*/site-packages/conda-*.egg-info/**/*
- lib/python*/site-packages/conda/**/*
- lib/python*/site-packages/conda_env-*.dist-info/**/*
- lib/python*/site-packages/conda_env-*.egg
- lib/python*/site-packages/conda_env-*.egg-info
- lib/python*/site-packages/conda_env-*.egg-info/**/*
- lib/python*/site-packages/conda_env/**/*
- lib/python2.7/site-packages/xonsh/conda.xsh
- lib/python2.7/site-packages/xontrib/conda.xsh
- lib/python3.5/site-packages/xonsh/conda.xsh
- lib/python3.6/site-packages/xonsh/conda.xsh
- lib/python3.6/site-packages/xontrib/conda.xsh
- lib/python3.7/site-packages/xonsh/conda.xsh
- lib/python3.7/site-packages/xontrib/conda.xsh
- lib/python3.8/site-packages/xontrib/conda.xsh
- lib/python3.9/site-packages/xontrib/conda.xsh
- shell/condabin/Conda.psm1
- shell/condabin/conda-hook.ps1
- site-packages/conda-*.dist-info/**/*
- site-packages/conda-*.egg-info/**/*
- site-packages/conda/**/*
- site-packages/conda_env-*.dist-info/**/*
- site-packages/conda_env-*.egg-info/**/*
- site-packages/conda_env/**/*
