name: mark-broken

on:
#   schedule:
#     - cron: "0 8 * * *"
  workflow_dispatch: null

jobs:
  mark-broken:
    name: mark-broken
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: configure git
        shell: bash -l {0}
        run: |
          python -m pip install -e .

          git config --global pull.rebase false
          git config --global user.name conda-forge-daemon
          git config --global user.email '64793534+conda-forge-daemon@users.noreply.github.com'

      - name: mark-broken
        shell: bash -l {0}
        run: |
          python scripts/make_admin_requests_broken_prs.py \
          --job-url="https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}"
        env:
          RUN_ID: ${{ github.run_id }}
          GH_TOKEN: ${{ secrets.CF_DAEMON_GH_TOKEN }}

      - name: push
        shell: bash -l {0}
        run: |
          git add scan_data/.
          git commit --allow-empty -am "[ci skip] mark broken for https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}"
          for _ in `seq 0 1`; do
            git pull
            git push
          done
        env:
          RUN_ID: ${{ github.run_id }}

      - name: bump on fail
        shell: bash -l {0}
        if: github.ref == 'refs/heads/master' && failure()
        run: |
          conda-forge-bump-on-fail \
            --job-name=${ACTION_NAME} \
            --job-url="https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}"
        env:
          GH_TOKEN: ${{ secrets.CF_DAEMON_GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          ACTION_NAME: ${{ github.workflow }}
