name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: install micromamba and code
        run: |
          rm -f ~/.bashrc
          rm -f ~/.bash_profile
          rm -f ~/.profile
          touch ~/.bashrc
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
          ./micromamba shell init -s bash -p ~/micromamba
          mkdir -p ~/micromamba/pkgs/
          echo 'set -eo pipefail' >> ~/.bashrc
          echo 'micromamba activate test' >> ~/.bashrc
          mv ~/.bashrc ~/.profile
          export MAMBA_ROOT_PREFIX=~/micromamba
          export MAMBA_EXE=$(pwd)/micromamba
          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
          micromamba create -f environment.yml -y
          micromamba activate test
          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 conda_forge_artifact_validation
          flake8 bin/*

      - name: test
        shell: bash -l {0}
        run: |
          pytest -vvs conda_forge_artifact_validation

      - name: run cli
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact --help
          conda-forge-generate-validate-yamls --help

      - name: run generate
        shell: bash -l {0}
        run: |
          conda-forge-generate-validate-yamls --test
          git diff

      - name: run validate
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact -v \
            https://anaconda.org/conda-forge/numpy/1.19.4/download/osx-64/numpy-1.19.4-py36hcf5569d_1.tar.bz2 \
            --md5sum="c792b85aebf54d48fb3d7597d6688ed6"

          wget https://anaconda.org/conda-forge/numpy/1.19.4/download/osx-64/numpy-1.19.4-py36hcf5569d_1.tar.bz2
          conda-forge-validate-artifact -v \
            numpy-1.19.4-py36hcf5569d_1.tar.bz2 \
            --md5sum="c792b85aebf54d48fb3d7597d6688ed6"
