name: tests

on:
  push: null
  pull_request: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda install --quiet --file requirements.txt
          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 conda_forge_artifact_validation
          flake8 bin/conda-forge-validate-artifact
          black --check conda_forge_artifact_validation
          black --check bin/conda-forge-validate-artifact

      - name: test
        shell: bash -l {0}
        run: |
          pytest -vvs conda_forge_artifact_validation

      - name: run cli
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact --help
          conda-forge-validate-artifact
