name: validate-artifact

on:
  repository_dispatch: null

jobs:
  validate-artifact:
    name: validate-artifact
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: install micromamba and code
        run: |
          rm -f ~/.bashrc
          rm -f ~/.bash_profile
          rm -f ~/.profile
          touch ~/.bashrc
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
          ./micromamba shell init -s bash -p ~/micromamba
          mkdir -p ~/micromamba/pkgs/
          echo 'set -eo pipefail' >> ~/.bashrc
          echo 'micromamba activate test' >> ~/.bashrc
          mv ~/.bashrc ~/.profile
          export MAMBA_ROOT_PREFIX=~/micromamba
          export MAMBA_EXE=$(pwd)/micromamba
          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
          micromamba create -f environment.yml -y
          micromamba activate test
          python -m pip install -e .

      - name: configure git
        shell: bash -l {0}
        run: |
          git config pull.rebase false
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: validate
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact -v --md5sum=${MD5} ${ARTIFACT_URL}
        env:
          MD5: ${{ github.event.client_payload.md5 }}
          ARTIFACT_URL: ${{ github.event.client_payload.artifact_url }}

      # - name: upload
      #   shell: bash -l {0}
      #   run: |
      #     :
      #   env:
      #     MD5: ${{ github.event.client_payload.md5 }}
      #     ARTIFACT_URL: ${{ github.event.client_payload.artifact_url }}

      # - name: bump on fail
      #   shell: bash -l {0}
      #   run: |
      #     git commit -am "[ci skip] scan data for https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}"
      #   env:
      #     RUN_ID: ${{ github.run_id }}
      #     MD5: ${{ github.event.client_payload.md5 }}
      #     ARTIFACT_URL: ${{ github.event.client_payload.artifact_url }}

      - name: bump on fail
        shell: bash -l {0}
        if: github.ref == 'refs/heads/master' && failure()
        run: |
          conda-forge-bump-on-fail \
            --job-name=${ACTION_NAME} \
            --job-url="https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}"
        env:
          GH_TOKEN: ${{ secrets.CF_DAEMON_GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          ACTION_NAME: ${{ github.workflow }}
