name: validate-artifact

on:
  repository_dispatch: null

jobs:
  validate-artifact:
    name: validate-artifact
    runs-on: "ubuntu-latest"
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - uses: actions/checkout@v2

      - name: install micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: configure git and install code
        shell: bash -l {0}
        run: |
          python -m pip install -e .

          git config --global pull.rebase false
          git config --global user.email '64793534+conda-forge-daemon@users.noreply.github.com'
          git config --global user.name 'conda-forge-daemon'

          repo_url=https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git remote set-url --push origin ${repo_url}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: validate
        shell: bash -l {0}
        run: |
          conda-forge-validate-artifact \
            -v \
            --feedstock=${FEEDSTOCK} \
            --md5sum=${MD5} \
            --job-url="https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}" \
            --git-sha=${GIT_SHA} \
            ${ARTIFACT_URL}
        env:
          RUN_ID: ${{ github.run_id }}
          MD5: ${{ github.event.client_payload.md5 }}
          ARTIFACT_URL: ${{ github.event.client_payload.artifact_url }}
          FEEDSTOCK: ${{ github.event.client_payload.feedstock }}
          GIT_SHA: ${{ github.event.client_payload.git_sha }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PROD_BINSTAR_TOKEN: ${{ secrets.PROD_BINSTAR_TOKEN }}
          STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}

      - name: bump on fail
        shell: bash -l {0}
        if: github.ref == 'refs/heads/master' && failure()
        run: |
          conda-forge-bump-on-fail \
            --job-name=${ACTION_NAME} \
            --job-url="https://github.com/conda-forge/artifact-validation/actions/runs/${RUN_ID}" \
            --artifact-url=${ARTIFACT_URL}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          RUN_ID: ${{ github.run_id }}
          ACTION_NAME: ${{ github.workflow }}
          ARTIFACT_URL: ${{ github.event.client_payload.artifact_url }}
